### ISSUE TITLE
1.3.70

### ISSUE THREAD

**Issue by timrijckaert** [kotest/kotest#1260]
It seems like no tests are run when I run `./gradlew test` with Kotlin verion 1.3.70.
It works perfectly on 1.3.61.

Running `4.0.0-BETA`

In IntelliJ it does work however

Any ideas?

**Comment by imanushin** [comment]
I received the following error for kotest 4.0 beta. Probably, the issue is with this.

```
org.junit.platform.commons.JUnitException: TestEngine with ID 'kotest' failed to discover tests
	at org.junit.platform.launcher.core.DefaultLauncher.discoverEngineRoot(DefaultLauncher.java:189)
	at org.junit.platform.launcher.core.DefaultLauncher.discoverRoot(DefaultLauncher.java:168)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:132)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
Caused by: java.lang.NoClassDefFoundError: kotlin/time/MonoClock
	at io.kotest.core.engine.TestDiscovery.scanUris(TestDiscovery.kt:137)
	at io.kotest.core.engine.TestDiscovery.discover(TestDiscovery.kt:66)
	at io.kotest.runner.junit5.KotestJunitPlatformTestEngine.discover(KotestJunitPlatformTestEngine.kt:63)
	at io.kotest.runner.junit5.KotestJunitPlatformTestEngine.discover(KotestJunitPlatformTestEngine.kt:21)
	at org.junit.platform.launcher.core.DefaultLauncher.discoverEngineRoot(DefaultLauncher.java:181)
	... 6 more
Caused by: java.lang.ClassNotFoundException: kotlin.time.MonoClock
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 11 more
```

**Comment by sksamuel** [comment]
Beta2 is released with 1.3.70 support.
