### ISSUE TITLE
Koin extension not working since Koin version 2.1.0

### ISSUE THREAD

**Issue by JoonasC** [kotest/kotest#1349]
It seems like the Koin extension is not working with version 2.1.5 of Koin.
The issue was introduced in version 2.1.0 of Koin.
Here is the gradle test output:
```
> Task :test
~~~ Kotest Configuration ~~~
-> Parallelism: 1 thread(s)
-> Default test timeout: 600000ms
-> Default test order: TestCaseOrder
-> Default isolation mode: IsolationMode
-> Global soft assertations: False
-> Write spec failure file: False
-> Fail on ignored tests: False
-> Spec execution order: LexicographicSpecExecutionOrder
-> Extensions
  - io.kotest.core.extensions.SystemPropertyTagExtension
  - io.kotest.core.extensions.RuntimeTagExtension
  - io.kotest.core.extensions.TagFilteredDiscoveryExtension

java.lang.NoClassDefFoundError: org/koin/core/context/GlobalContextKt
java.lang.NoClassDefFoundError: org/koin/core/context/GlobalContextKt
java.lang.NoClassDefFoundError: org/koin/core/context/GlobalContextKt
java.lang.NoClassDefFoundError: org/koin/core/context/GlobalContextKt
java.lang.NoClassDefFoundError: org/koin/core/context/GlobalContextKt
java.lang.NoClassDefFoundError: org/koin/core/context/GlobalContextKt
BUILD SUCCESSFUL in 9s
```

Here is my `build.gradle.kts` file:
```kotlin
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

val ktorVersion: String by project
val kotlinVersion: String by project
val logbackVersion: String by project
val koinVersion: String by project
val hikariCPVersion: String by project
val postgreSQLVersion: String by project
val ktormVersion: String by project
val jBCryptVersion: String by project
val valiktorVersion: String by project
val kotestVersion: String by project
val mockKVersion: String by project
val testcontainersVersion: String by project

plugins {
    application
    kotlin("jvm")
    id("org.jlleitschuh.gradle.ktlint")
}

group = "com.company.project"
version = "1.0"

application {
    mainClassName = "io.ktor.server.netty.EngineMain"
}

repositories {
    mavenLocal()
    mavenCentral()
    jcenter()
    maven { url = uri("https://kotlin.bintray.com/ktor") }
    flatDir {
        dirs = mutableSetOf(File("libs"))
    }
}

dependencies {
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlinVersion")
    implementation("io.ktor:ktor-server-netty:$ktorVersion")
    implementation("ch.qos.logback:logback-classic:$logbackVersion")
    implementation("io.ktor:ktor-server-core:$ktorVersion")
    implementation("io.ktor:ktor-server-host-common:$ktorVersion")
    implementation("io.ktor:ktor-auth:$ktorVersion")
    implementation("io.ktor:ktor-auth-jwt:$ktorVersion")
    implementation("io.ktor:ktor-jackson:$ktorVersion")
    implementation("org.koin:koin-core:$koinVersion")
    implementation("org.koin:koin-ktor:$koinVersion")
    implementation("org.koin:koin-logger-slf4j:$koinVersion")
    implementation("com.zaxxer:HikariCP:$hikariCPVersion")
    implementation("org.postgresql:postgresql:$postgreSQLVersion")
    implementation("me.liuwj.ktorm:ktorm-core:$ktormVersion")
    implementation("me.liuwj.ktorm:ktorm-support-postgresql:$ktormVersion")
    implementation("org.mindrot:jbcrypt:$jBCryptVersion")
    implementation("org.valiktor:valiktor-core:0.9.0")
    testImplementation("io.ktor:ktor-server-tests:$ktorVersion")
    testImplementation("org.koin:koin-test:$koinVersion")
    testImplementation("io.kotest:kotest-runner-junit5-jvm:$kotestVersion")
    testImplementation("io.kotest:kotest-assertions-core-jvm:$kotestVersion")
    testImplementation("io.kotest:kotest-extensions-koin-jvm:$kotestVersion")
    testImplementation("io.mockk:mockk:$mockKVersion")
    testImplementation("org.testcontainers:testcontainers:$testcontainersVersion")
    testImplementation("org.testcontainers:postgresql:$testcontainersVersion")
}

tasks.withType<KotlinCompile> {
    kotlinOptions.jvmTarget = "1.8"
}

tasks.withType<KotlinCompile>().all {
    kotlinOptions.freeCompilerArgs += "-Xuse-experimental=io.ktor.util.KtorExperimentalAPI"
}

tasks.withType<Test> {
    useJUnitPlatform()
}

kotlin.sourceSets["main"].kotlin.srcDirs("src/main")
kotlin.sourceSets["test"].kotlin.srcDirs("src/test")

sourceSets["main"].resources.srcDirs("src/main/resources")
sourceSets["test"].resources.srcDirs("src/test/resources")

```

Here is the test class:
```kotlin
class UserApiTests : KoinTest, StringSpec() {
    private val passwordHashForTestUsers = "\$2a\$14\$2Wc8XJjDqrQOTop.gR6PSeeIk2RKhv7..zRI2t1Pr1SO8y8t4/Kei"

    override fun listeners() = listOf(KoinListener(KoinModuleLists.DEFAULT))

    init {
        afterTest {
            val database: Database by inject()

            // Clean database up after tests
            database.useTransaction {
                database.sequenceOf(Projects).clear()
                database.sequenceOf(Users).clear()
            }

            // Shut down the HikariCP pool
            val hikariDataSource: HikariDataSource by inject()
            hikariDataSource.close()
        }
        "Login request to user API with too long username should fail" {
            val objectMapper: ObjectMapper by inject()

            withDefaultTestApplication {
                val call: TestApplicationCall = handleRequest(HttpMethod.Post, "/api/v1/user/login") {
                    addHeader(HttpHeaders.ContentType, ContentType.Application.Json.toString())

                    setBody(
                        objectMapper.writeValueAsString(
                            LoginRequest(
                                "thisusernameiswaytooooolooooooong",
                                "testpassword",
                                true
                            )
                        )
                    )
                }

                call.response.status() shouldBe HttpStatusCode.BadRequest
                call.response.content shouldNotBe null

                val response: Response = objectMapper.readValue(call.response.content, Response::class.java)
                response.error?.message shouldBe "Constraint violation for parameter username: Size must be between 3 and 10"
            }
        }
    }
}
```

As a side note, I am testing a Ktor project, which is using the Ktor extension of Koin ([https://doc.insert-koin.io/#/koin-ktor/ktor](https://doc.insert-koin.io/#/koin-ktor/ktor)), but I don't install the Koin feature when testing, and instead let Kotest start the Koin application with the Koin listener.
Not sure if that has anything to do with the issue.

**Comment by LeoColman** [comment]
Thanks for the report!
I'll take a look into this
