### ISSUE TITLE
Error while running mvn test target: java.lang.NoSuchMethodError: 'io.github.classgraph.ClassGraph io.github.classgraph.ClassGraph.rejectPackages(java.lang.String[])'

### ISSUE THREAD

**Issue by peter-majeed** [kotest/kotest#2182]
Since upgrading from Kotlin version 1.3.70 to 1.4.31, when running `mvn test`, we get this exception.

> org.apache.maven.surefire.util.SurefireReflectionException: java.util.ServiceConfigurationError: org.junit.platform.engine.TestEngine: Provider io.kotest.runner.junit.platform.KotestJunitPlatformTestEngine could not be instantiated

> Caused by: java.util.ServiceConfigurationError: org.junit.platform.engine.TestEngine: Provider io.kotest.runner.junit.platform.KotestJunitPlatformTestEngine could not be instantiated

> Caused by: java.lang.NoSuchMethodError: 'io.github.classgraph.ClassGraph io.github.classgraph.ClassGraph.rejectPackages(java.lang.String[])'
	at io.kotest.engine.config.DetectConfigKt.detectConfig(detectConfig.kt:28)

Below is a snippet of our mvn configuration.

```
<dependencies>
  <dependency>
    <groupId>org.jetbrains.kotlin</groupId>
    <artifactId>kotlin-stdlib-jdk8</artifactId>
    <version>${kotlin.version}</version>
    <scope>compile</scope>
  </dependency>
  <dependency>
    <groupId>org.jetbrains.kotlin</groupId>
    <artifactId>kotlin-script-runtime</artifactId>
    <version>${kotlin.version}</version>
    <scope>compile</scope>
  </dependency>
  <dependency>
    <groupId>org.junit.jupiter</groupId>
    <artifactId>junit-jupiter-engine</artifactId>
    <version>5.7.1</version>
  </dependency>
  <dependency>
    <groupId>io.kotest</groupId>
    <artifactId>kotest-runner-junit5-jvm</artifactId>
    <version>4.4.3</version>
  </dependency>
  <dependency>
    <groupId>io.kotest</groupId>
    <artifactId>kotest-assertions-core-jvm</artifactId>
    <version>4.4.3</version>
  </dependency>
  <dependency>
    <groupId>io.kotest</groupId>
    <artifactId>kotest-assertions-jvm</artifactId>
    <version>4.0.7</version>
  </dependency>
  <dependency>
    <groupId>io.kotest</groupId>
    <artifactId>kotest-core-jvm</artifactId>
    <version>4.1.3</version>
  </dependency>
</dependencies>
```

We're using `maven-surefire-plugin v.2.22.2`. Having had a quick look, it _does_ appear that `io.github.classgraph.ClassGraph.rejectPackages` still exists @ https://github.com/classgraph/classgraph/blob/latest/src/main/java/io/github/classgraph/ClassGraph.java. Does anyone have a sense as to what can be done to get past this error, or why this is failing only now?

**Comment by sksamuel** [comment]
My guess is something to do with the mismatched versions you have there.
You don't need `kotest-core-jvm` so you can remove that.
You can remove `kotest-assertions-jvm as well.

**Comment by peter-majeed** [comment]
Thanks. For now, I'll close out this ticket without a resolution. We've moved our application to use kotlin.test in the interim. I do appreciate this library, so at some point I'll look into the suggestions you mentioned.

**Comment by sksamuel** [comment]
I'm 99% sure it was caused by having version mismatches (you had 4.4.3 4.07 and 4.1.3 mixed up in there). If you ever come back to using Kotest again in the future feel free to reach out.

**Comment by PAenugula** [comment]
Hi, I'm using Gradle and Kotest 4.4.3 with matching versions throughout, but still getting a similar issue where the kotest could not get instantiated. Any more insight to this issue?

**Comment by sksamuel** [comment]
Something must be bumping or downgrading the classpath version on your
build.

**Comment by fcabouat** [comment]
Hi,

Wasn't all too obvious in my case what the error was (didn't think classpath was an actual dependency here, and not *the java classpath* ).

Help with maven dependency:tree plugin and :

```
  <dependency>
  <groupId>org.javers</groupId>
  <artifactId>javers-core</artifactId>
  <version>${javers.version}</version>
  <exclusions>
	  <exclusion>
		  <groupId>io.github.classgraph</groupId>
		  <artifactId>classgraph</artifactId>
	  </exclusion>
  </exclusions>
  </dependency>
```

fixed it.

**Comment by rgmz** [comment]
The error wasn't obvious in my case either; I'm including some verbose output to (hopefully) improve the 'searchability' of the error.

Running the tests via terminal (`mvn test`) yielded a vague error:

> Provider io.kotest.runner.junit.platform.KotestJunitPlatformTestEngine could not be instantiated

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  11.368 s
[INFO] Finished at: 2021-08-19T07:32:51-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project REDACTED: There are test failures.
[ERROR] 
[ERROR] Please refer to /Users/REDACTED/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] There was an error in the forked process
[ERROR] java.util.ServiceConfigurationError: org.junit.platform.engine.TestEngine: Provider io.kotest.runner.junit.platform.KotestJunitPlatformTestEngine could not be instantiated
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process
[ERROR] java.util.ServiceConfigurationError: org.junit.platform.engine.TestEngine: Provider io.kotest.runner.junit.platform.KotestJunitPlatformTestEngine could not be instantiated
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:656)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:282)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:245)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1183)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1011)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:857)
[ERROR]         at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR]         at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
[ERROR]         at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
[ERROR]         at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
[ERROR]         at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
[ERROR]         at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

I stumbled across this issue but, similar to @fcabouat, didn't initially realize the relevance of `io.github.classgraph`. However, running the tests from my IDE (IntelliJ) returned the _actual_ error, which confirmed that classgraph was the root cause:
> [java.lang.NoSuchMethodError: 'io.github.classgraph.ClassGraph io.github.classgraph.ClassGraph.rejectPackages(java.lang.String[])']

---

Running `mvn dependency:tree` and searching for `classgraph` revealed that another dependency, `org.springdoc:springdoc-openapi-kotlin`, was causing the conflict:
```
[INFO] +- org.springdoc:springdoc-openapi-kotlin:jar:1.5.9:compile
[INFO] |  +- org.springdoc:springdoc-openapi-common:jar:1.5.9:compile
[INFO] |  |  +- io.swagger.core.v3:swagger-models:jar:2.1.9:compile
[INFO] |  |  +- io.swagger.core.v3:swagger-annotations:jar:2.1.9:compile
[INFO] |  |  +- io.swagger.core.v3:swagger-integration:jar:2.1.9:compile
[INFO] |  |  |  \- io.swagger.core.v3:swagger-core:jar:2.1.9:compile
[INFO] |  |  |     +- jakarta.xml.bind:jakarta.xml.bind-api:jar:2.3.3:compile
[INFO] |  |  |     |  \- jakarta.activation:jakarta.activation-api:jar:1.2.2:compile
[INFO] |  |  |     +- com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.12.4:compile
[INFO] |  |  |     +- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.12.4:compile
[INFO] |  |  |     \- jakarta.validation:jakarta.validation-api:jar:2.0.2:compile
[INFO] |  |  +- io.github.classgraph:classgraph:jar:4.8.69:compile
[INFO] |  |  \- org.apache.commons:commons-lang3:jar:3.12.0:compile
```

Creating an exclusion rule resolved the issue. Thus far, I haven't noticed any ill effects from this. :) 
```
<dependency>
    <groupId>org.springdoc</groupId>
    <artifactId>springdoc-openapi-kotlin</artifactId>
    <version>${springdoc.version}</version>
    <exclusions>
        <exclusion>
            <groupId>io.github.classgraph</groupId>
            <artifactId>classgraph</artifactId>
        </exclusion>
    </exclusions>
</dependency>
```

**Comment by rgmz** [comment]
> Creating an exclusion rule resolved the issue. Thus far, I haven't noticed any ill effects from this. :)

**Update:** Unfortunately, it wasn't as simple as this.

The exclusion rule allows Kotest to start, but causes the application to fail once started:
```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.web.reactive.HandlerMapping]: Factory method 'resourceHandlerMapping' threw exception; nested exception is java.lang.NoClassDefFoundError: io/github/classgraph/ClassGraph
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.3.9.jar:5.3.9]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653) ~[spring-beans-5.3.9.jar:5.3.9]
        ... 34 common frames omitted
Caused by: java.lang.NoClassDefFoundError: io/github/classgraph/ClassGraph
        at org.webjars.WebJarAssetLocator.<init>(WebJarAssetLocator.java:150) ~[webjars-locator-core-0.46.jar:na]
        at org.springframework.web.reactive.resource.WebJarsResourceResolver.<init>(WebJarsResourceResolver.java:61) ~[spring-webflux-5.3.9.jar:5.3.9]
        at org.springframework.web.reactive.config.ResourceChainRegistration.getResourceResolvers(ResourceChainRegistration.java:114) ~[spring-webflux-5.3.9.jar:5.3.9]
        at org.springframework.web.reactive.config.ResourceHandlerRegistration.getRequestHandler(ResourceHandlerRegistration.java:189) ~[spring-webflux-5.3.9.jar:5.3.9]
        at org.springframework.web.reactive.config.ResourceHandlerRegistry.getRequestHandler(ResourceHandlerRegistry.java:149) ~[spring-webflux-5.3.9.jar:5.3.9]
        at org.springframework.web.reactive.config.ResourceHandlerRegistry.getHandlerMapping(ResourceHandlerRegistry.java:140) ~[spring-webflux-5.3.9.jar:5.3.9]
        at org.springframework.web.reactive.config.WebFluxConfigurationSupport.resourceHandlerMapping(WebFluxConfigurationSupport.java:246) ~[spring-webflux-5.3.9.jar:5.3.9]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.3.9.jar:5.3.9]
        ... 35 common frames omitted
Caused by: java.lang.ClassNotFoundException: io.github.classgraph.ClassGraph
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581) ~[na:na]
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[na:na]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[na:na]
        ... 47 common frames omitted
```

Digging deeper, the root cause is [Classgraph v4.8.86](https://github.com/classgraph/classgraph/releases/tag/classgraph-4.8.86) which [replaces all references to "whitelist" and "blacklist"](https://github.com/classgraph/classgraph/commit/1f81a3d58f7e888005fde98d537ad691d26404d8) (arguably a breaking change). This is frustrating because it makes Kotest incompatible with Classgraph < 4.8.86, as `ClassGraph.blacklistPackages(java.lang.String[])`  exists but `ClassGraph.rejectPackages(java.lang.String[])` does not (despite being functionally compatible).

Any suggestions for how this can be remedied? (I'll try and get the version bumped for SpringDoc, but that will take time.)

**Comment by sksamuel** [comment]
I think the easist fix is for kotest to use the deprecated older names.
I can do that and release 4.6.2

**Comment by rgmz** [comment]
> I think the easist fix is for kotest to use the deprecated older names.
I can do that and release 4.6.2

Thanks, @sksamuel. I agree it seems the easiest fix to preserve compatibility with Classgraph 4.8.x.

---

For what it's worth, pinning a higher version of Classgraph [`<dependencyManagement>`](https://stackoverflow.com/a/46348737)  _\*appears to\*_ work. However, there may be subtle issues I'm yet to discover, and there may be other package conflicts which cannot be resolved by this.

```xml
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>io.github.classgraph</groupId>
            <artifactId>classgraph</artifactId>
            <version>4.8.105</version>
        </dependency>
    </dependencies>
</dependencyManagement>
```

**Comment by sksamuel** [comment]
Updated in 4.6.2

**Comment by sheetalj2205** [comment]
Can anyone tell me is this issue is related to the version of `com.github.ben-manes.caffeine:caffeine` ?
