### ISSUE TITLE
java.lang.NoClassDefFoundError: io/kotest/matchers/jvmerrorcollector

### ISSUE THREAD

**Issue by helpermethod** [kotest/kotest#5727]
**Which version of Kotest are you using**

6.1.4

After upgrading from 6.1.3 to 6.1.4 I am getting the following error

```
io/kotest/matchers/jvmerrorcollector
java.lang.NoClassDefFoundError: io/kotest/matchers/jvmerrorcollector
	at de.glasfaserplus.common.test.extension.ControllerTestExtensionFunctionsKt.shouldHavePath(ControllerTestExtensionFunctions.kt:160)
```

**Comment by helpermethod** [comment]
This was a problem on our side, sorry for the inconvenience :)

**Comment by christopherfrieler** [comment]
I'm getting a very similar error.

@helpermethod , what was the cause in your case?

**Comment by christopherfrieler** [comment]
Ok, found it. Due to a mistake in my dependencies I had version 6.1.3 and 6.1.4 both on the classpath.

@helpermethod Nevermind ;-)

**Comment by helpermethod** [comment]
@christopherfrieler Sorry for the late response, that was also my problem. Glad you resolved it!

**Comment by matejdro** [comment]
Hm, this is not ideal, it seems kotest regularly breaks binary compatibility?

**Comment by sksamuel** [comment]
@matejdro

We made a mistake in the 6 series by changing a public package, even though that package is never used by end users. In 6.1.4 we reverted this mistake. As long as users are using the same Kotest version for all Kotest deps, there are no issues.

I apologize for any inconvenience. It's not something we take lightly and we'll not do it again. We're adding better api checks to avoid. 

Again sorry for the mistake.

**Comment by matejdro** [comment]
Thanks for the explanation!
