### ISSUE TITLE
kotest-assertions-kotlinx-time:4.4.3 not compatible with kotest:5.6.2

### ISSUE THREAD

**Issue by mnonnenmacher** [kotest/kotest#3564]
**Which version of Kotest are you using**
5.6.2

When using `kotest-assertions-kotlinx-time:4.4.3` with Kotest 5.6.2 the `Instant.shouldBeBetween` extension function fails with:
`java.lang.NoSuchMethodError: 'void io.kotest.matchers.ShouldKt.shouldBe(java.lang.Object, java.lang.Object)'`

It was working fine with Kotest 5.5.5.

**Comment by matejdro** [comment]
Yeah, it looks like there was a binary breaking change.

**Comment by Kantis** [comment]
Can you update your dependency to `io.kotest.extensions:kotest-assertions-kotlinx-datetime:1.0.1`?

**Comment by matejdro** [comment]
Personally, I don't think the issue here is specifically kotlinx-time, but the fact that a binary breaking change was introduced without any mentions in the changelogs, requiring all libraries that use kotest internally to be re-released with new version.

**Comment by sksamuel** [comment]
I've released version 1.1.0 of our time library updated for the latest kotest. So that should fix any issues.

`io.kotest.extensions:kotest-assertions-kotlinx-datetime:1.1.0`

**Comment by mnonnenmacher** [comment]
Thank you very much @sksamuel.
