### ISSUE TITLE
Compilation for kotlin/native and kotlin/js fails with kotlin 1.7.20 and kotest 5.4.2

### ISSUE THREAD

**Issue by juh9870** [kotest/kotest#3173]
**Which version of Kotest are you using** - 5.4.2

I'm getting the following issue when tyrying to compile for js or native targets:
```
Compilation failed: org.jetbrains.kotlin.backend.common.ir.IrUtilsKt.addChild(Lorg/jetbrains/kotlin/ir/declarations/IrDeclarationContainer;Lorg/jetbrains/kotlin/ir/declarations/IrDeclaration;)V

 * Source files: BundleTest.kt
 * Compiler version info: Konan: 1.7.20-Beta / Kotlin: 1.7.20
 * Output kind: LIBRARY
 ```
 This error appeared after I added kotest to `scrapyard-utils` module
 
Repository:
https://gitfront.io/r/juh9870/wzWHt7gwZ73c/match3kt/

**Comment by ghost** [comment]
I can reproduce. However, downgrading to Kotlin 1.7.10 seems to make it work perfectly

**Comment by juh9870** [comment]
Yes, it works on 1.7.10, but I use it for unit tests for my KorGE tests, and KorGE requires 1.7.20, so I can't run both atm. I've temporary disabled client part and rolled back to 1.7.10, but that's not a long-term solution

**Comment by sksamuel** [comment]
https://youtrack.jetbrains.com/issue/KT-53750/Breaking-change-in-IR-API-from-1710-to-1720

**Comment by sksamuel** [comment]
Fixed in 5.5.0

**Comment by idugalic** [comment]
Thank you!

Is only a `io.kotest.multiplatform` gradle plugin being released with 5.5.0 version?
What about libraries `io.kotest:kotest-framework-engine`...? Should we continue using 5.4.2?

**Comment by sksamuel** [comment]
All should be on 5.5.0
