### ISSUE TITLE
Cannot launch tests with latest kotest plugin and framework

### ISSUE THREAD

**Issue by NikolayMetchev** [kotest/kotest#5453]
Using plugin version 1.0.5
kotest version 4.3.2
kotest-runner-console-jvm version 4.1.3.2
I get the following when I launch a test:
```
Testing started at 10:38 ...
Error: Unable to initialize main class io.kotest.runner.console.LauncherKt
Caused by: java.lang.NoClassDefFoundError: io/kotest/core/engine/TestEngineListener

Process finished with exit code 1
```

Seems like that class has moved

**Comment by sksamuel** [comment]
You don't need the console dependency.
Just add kotest-engine-jvm or kotest-runner-junit5-jvm
Where did you read about console? I will correct the docs.

**Comment by bryan-nz** [comment]
I'm not sure if this is related, but I was just trying the 2021.1 EAP version of intellij with kotest 4.3.1 and plugin 1.0.5 And I'm seeing this error:
16:06	Kotest
Add io.kotest:kotest-runner-console-jvm to your build to execute tests using the kotest plugin. Required version is 4.1.0 or higher.

**Comment by sksamuel** [comment]
Sounds like an old warning message. I'll fix that thanks.

**Comment by NikolayMetchev** [comment]
I see, I was getting that error so I added that dep. I guess the latest EAP breaks the pluging

**Comment by xmlking** [comment]
I already have kotestVersion=4.4.0. testing with intelliJ 2021.1 EAP

![image](https://user-images.githubusercontent.com/627951/106815587-ee706380-6628-11eb-8706-43b0e7580f4f.png)

**Comment by sksamuel** [comment]
The intellij plugin doesn't work with 2021.1 EAP yet.

**Comment by sksamuel** [comment]
A new version of the plugin that supports 2021.1 EAP has been uploaded. It usually takes Jetbrains 1-2 working days to approve the release - so hopefully by close of business Monday it will be in the marketplace, if not then Tuesday.
