### ISSUE TITLE
NoSuchMethodError: kotlin.time.DurationKt.toDuration with version 5.3.1 when testing Gradle plugins

### ISSUE THREAD

**Issue by DanySK** [kotest/kotest#3059]
Hi,
I tried to update Kotest to 5.3.1, but I could not in projects testing Gradle plugins, for instance https://github.com/DanySK/Template-for-Gradle-Plugins, on the branch [`renovate/patch-kotest`](https://github.com/DanySK/Template-for-Gradle-Plugins/tree/renovate/patch-kotest).

Here is the build scan of the failing build: https://scans.gradle.com/s/fyvjl7xhjrazm/failure?anchor=e30&expanded-stacktrace=WyIwIl0&focused-exception-line=0-0#1

I guess that there is some feature of a recent version of Kotlin being used by Kotest 5.3.1 and not present in the version of Kotlin that Gradle embeds.

**Comment by Kantis** [comment]
Seems to be caused by 
```

Exception
java.lang.NoSuchMethodError: kotlin.time.DurationKt.toDuration(JLkotlin/time/DurationUnit;)J	
at io.kotest.engine.spec.interceptor.SpecFinishedInterceptor.intercept-0E7RQCE(SpecFinishedInterceptor.kt:22)	
•••
at io.kotest.runner.junit.platform.KotestJunitPlatformTestEngine.execute(KotestJunitPlatformTestEngine.kt:82)	
at io.kotest.runner.junit.platform.KotestJunitPlatformTestEngine.execute(KotestJunitPlatformTestEngine.kt:46)	
•••
```

I guess Gradle 7.4.2 still embeds Kotlin 1.5.31?

**Comment by DanySK** [comment]
This is very much possible indeed

**Comment by Kantis** [comment]
I guess this wasn't working on 5.x.x ? Kotest requires Kotlin 1.6 since 5.0.0 (see https://kotest.io/docs/changelog.html#kotlin-16-is-now-the-minimum-supported-version)

**Comment by sksamuel** [comment]
This is a duplicate of https://github.com/kotest/kotest/issues/2804
It's because gradle embed a kotlin version. It causes lots of issues.

**Comment by sksamuel** [comment]
https://github.com/gradle/gradle/issues/16345

**Comment by DanySK** [comment]
@sksamuel It can't be an exact duplicate, as it works with Kotest 5.3.0: https://github.com/DanySK/Template-for-Gradle-Plugins/blob/master/gradle/libs.versions.toml

**Comment by charleskorn** [comment]
I am seeing a similar issue as well - my Gradle plugin tests are failing with 5.3.1 and 5.3.2, but passed with 5.3.0.

**Comment by charleskorn** [comment]
It looks like Gradle 7.5 upgrades the embedded version of Kotlin to 1.6.10 🎉  https://github.com/gradle/gradle/pull/19539

**Comment by DanySK** [comment]
Tested, confirmed. Issue solved.
