### ISSUE TITLE
NoSuchMethodError on test execution after update to 4.2.

### ISSUE THREAD

**Issue by joelhess** [kotest/kotest#1641]
Just updated from 4.1.2 to 4.2.  Running from gradle 6.4.
```
ExampleTest STANDARD_ERROR
    java.lang.NoSuchMethodError: 'void kotlin.jvm.internal.FunctionReferenceImpl.<init>(int, java.lang.Class, java.lang.String, java.lang.String, int)'
    	at io.kotest.engine.runners.SingleInstanceSpecRunner$runTest$testExecutor$3.<init>(SingleInstanceSpecRunner.kt)
    	at io.kotest.engine.runners.SingleInstanceSpecRunner$runTest$testExecutor$3.<clinit>(SingleInstanceSpecRunner.kt)
    	at io.kotest.engine.runners.SingleInstanceSpecRunner.runTest(SingleInstanceSpecRunner.kt:71)
    	at io.kotest.engine.runners.SingleInstanceSpecRunner$execute$2$invokeSuspend$$inlined$invoke$lambda$1.invokeSuspend(SingleInstanceSpecRunner.kt:83)
    	at io.kotest.engine.runners.SingleInstanceSpecRunner$execute$2$invokeSuspend$$inlined$invoke$lambda$1.invoke(SingleInstanceSpecRunner.kt)
    	at io.kotest.engine.spec.SpecRunner$runParallel$$inlined$map$lambda$2$1.invokeSuspend(SpecRunner.kt:80)
    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
    	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
    	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:84)
    	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
    	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
    	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
    	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
    	at io.kotest.engine.spec.SpecRunner$runParallel$$inlined$map$lambda$2.run(SpecRunner.kt:79)
    	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    	at java.base/java.lang.Thread.run(Thread.java:834)
```
I have a project config that specifies InstancePerTest as the isolation Mode.

```
class KotestProjectConfig : AbstractProjectConfig() {
    override val isolationMode = IsolationMode.InstancePerTest
    override val globalAssertSoftly = true
}
```

Test Looks like: 
```
class ExampleTest : StringSpec() {
    init {
        "Example Set" {
            val exampleTest = Example("testVal")
            exampleTest.myProperty.shouldBe("testVal")
        }
    }
}
```

**Comment by sksamuel** [comment]
Dup of https://github.com/kotest/kotest/issues/5486 I think

**Comment by sksamuel** [comment]
Once the latest plugin is approved by jetbrains (tomorrow morning I hope) all will be good.
You can install manually if you like in the meantime.
[kotest-plugin-intellij-1.1.0-SNAPSHOT-IC-2020.1.zip](https://github.com/kotest/kotest/files/5104804/kotest-plugin-intellij-1.1.0-SNAPSHOT-IC-2020.1.zip)

**Comment by sksamuel** [comment]
And this one for Android Studio or Intellij 2019.
[kotest-plugin-intellij-1.1.0-SNAPSHOT-IC-2019.3.zip](https://github.com/kotest/kotest/files/5104869/kotest-plugin-intellij-1.1.0-SNAPSHOT-IC-2019.3.zip)

**Comment by joelhess** [comment]
I see this from my CI system. No Intellij in sight there. Just Gradle.

**Comment by sksamuel** [comment]
Ah right yes, sorry had quite a few of these reports over the plugin so I just saw the exception and assumed.

**Comment by sksamuel** [comment]
Is there a mistake in the dummy test you've pasted up, because you're using InstancePerTest in config, but the exception is happening in the single instance test runner.

**Comment by sksamuel** [comment]
Also it seems like you maybe still have an old version of kotest floating about your build. You should only need assertions-core-jvm (if you use kotest assertions) and junit5-jvm.

**Comment by joelhess** [comment]
Sorry, I have it multiple projects. The one that failed does not have the isolation mode set, and so is just using the default. I've done a `gradle clean` to clear out any cruft, and ran `gradle --refresh-dependencies` to ensure that I have the right bits.
I just have these two in my build file:
```
testImplementation("io.kotest:kotest-runner-junit5-jvm:${Versions.kotest}")
testImplementation("io.kotest:kotest-assertions-core-jvm:${Versions.kotest}")
```
where Versions.kotest is set to "4.2.0"

If I disable the tests for that project and allow the other to run (with the isolation mode set) I get this:
```
    java.lang.NoSuchMethodError: 'void kotlin.jvm.internal.FunctionReferenceImpl.<init>(int, java.lang.Class, java.lang.String, java.lang.String, int)'
        at io.kotest.engine.runners.InstancePerTestSpecRunner$run$2$testExecutor$3.<init>(InstancePerTestSpecRunner.kt)
        at io.kotest.engine.runners.InstancePerTestSpecRunner$run$2$testExecutor$3.<clinit>(InstancePerTestSpecRunner.kt)
        at io.kotest.engine.runners.InstancePerTestSpecRunner$run$2.invokeSuspend(InstancePerTestSpecRunner.kt:147)
        at io.kotest.engine.runners.InstancePerTestSpecRunner$run$2.invoke(InstancePerTestSpecRunner.kt)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
        at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:194)
        at io.kotest.engine.runners.InstancePerTestSpecRunner.run(InstancePerTestSpecRunner.kt:113)
        at io.kotest.engine.runners.InstancePerTestSpecRunner.interceptAndRun(InstancePerTestSpecRunner.kt:107)
        at io.kotest.engine.runners.InstancePerTestSpecRunner.executeInCleanSpec(InstancePerTestSpecRunner.kt:98)
        at io.kotest.engine.runners.InstancePerTestSpecRunner$execute$$inlined$invoke$lambda$1.invokeSuspend(InstancePerTestSpecRunner.kt:77)
        at io.kotest.engine.runners.InstancePerTestSpecRunner$execute$$inlined$invoke$lambda$1.invoke(InstancePerTestSpecRunner.kt)
        at io.kotest.engine.spec.SpecRunner$runParallel$$inlined$map$lambda$2$1.invokeSuspend(SpecRunner.kt:80)
        (Coroutine boundary)
        at io.kotest.engine.runners.InstancePerTestSpecRunner.interceptAndRun(InstancePerTestSpecRunner.kt:107)
        at io.kotest.engine.runners.InstancePerTestSpecRunner.executeInCleanSpec(InstancePerTestSpecRunner.kt:98)
    Caused by: java.lang.NoSuchMethodError: 'void kotlin.jvm.internal.FunctionReferenceImpl.<init>(int, java.lang.Class, java.lang.String, java.lang.String, int)'
        at io.kotest.engine.runners.InstancePerTestSpecRunner$run$2$testExecutor$3.<init>(InstancePerTestSpecRunner.kt)
        at io.kotest.engine.runners.InstancePerTestSpecRunner$run$2$testExecutor$3.<clinit>(InstancePerTestSpecRunner.kt)
        at io.kotest.engine.runners.InstancePerTestSpecRunner$run$2.invokeSuspend(InstancePerTestSpecRunner.kt:147)
        at io.kotest.engine.runners.InstancePerTestSpecRunner$run$2.invoke(InstancePerTestSpecRunner.kt)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
        at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:194)
        at io.kotest.engine.runners.InstancePerTestSpecRunner.run(InstancePerTestSpecRunner.kt:113)
        at io.kotest.engine.runners.InstancePerTestSpecRunner.interceptAndRun(InstancePerTestSpecRunner.kt:107)
        at io.kotest.engine.runners.InstancePerTestSpecRunner.executeInCleanSpec(InstancePerTestSpecRunner.kt:98)
        at io.kotest.engine.runners.InstancePerTestSpecRunner$execute$$inlined$invoke$lambda$1.invokeSuspend(InstancePerTestSpecRunner.kt:77)
        at io.kotest.engine.runners.InstancePerTestSpecRunner$execute$$inlined$invoke$lambda$1.invoke(InstancePerTestSpecRunner.kt)
        at io.kotest.engine.spec.SpecRunner$runParallel$$inlined$map$lambda$2$1.invokeSuspend(SpecRunner.kt:80)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:84)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
        at io.kotest.engine.spec.SpecRunner$runParallel$$inlined$map$lambda$2.run(SpecRunner.kt:79)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by sksamuel** [comment]
Which version of Kotlin? It still looks to me like it's trying to create a 4.1.x version of the spec runner, but I could be wrong.

**Comment by joelhess** [comment]
1.3.72 on Java 11

**Comment by sksamuel** [comment]
Ok looks like in 1.4 they added some methods in FunctionReferenceImpl that aren't present in 1.3.72.
I've pushed a change to avoid the use of functon references, which should hopefully fix it.
You can try the snapshot once it builds.

**Comment by sksamuel** [comment]
Fixed in master, 4.2.1 will be released shortly.

**Comment by henrik242** [comment]
@sksamuel Is 4.2.1 just around the corner? 😄

**Comment by sksamuel** [comment]
4.2.1 is released, sorry for the delay.
