### ISSUE TITLE
The candidates arg must be provided

### ISSUE THREAD

**Issue by jtonic** [kotest/kotest#5338]
Running all test in a package works fine using kotest lib version **6.0.0-M1** but doesn't work any longer with recent versions.

The error is:

```
Exception in thread "main" java.lang.IllegalStateException: The candidates arg must be provided
	at io.kotest.engine.launcher.MainKt.main(main.kt:61)
```

Reproduced with:

IntelliJ IDEA 2025.1.1.1 (Ultimate Edition)
Build #IU-251.25410.129, built on May 9, 2025
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 15.5
Kotlin plugin: K2 mode
Registry:
Non-Bundled Plugins:
  kotest-plugin-intellij (1.3.95-2025.1)
Kotlin: 251.25410.129-IJ

Maven configuration:

```xml
<kotest.version>6.0.0.M2</kotest.version>

<dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.kotest</groupId>
                <artifactId>kotest-bom</artifactId>
                <version>${kotest.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
</dependencyManagement>
```

Probably not related to this but I've noticed that when I used a newer kotest version I had a compilation error for `testCase.name.**testName**`  and replaced with `testCase.name.**name**`

**Comment by sksamuel** [comment]
Fixed in latest, thanks.
